// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1RbW4Wd6lPrnuD3g0xFrJ_Zj7y558W5w',
    appId: '1:72597800908:web:b548b6ee1e52609505bf69',
    messagingSenderId: '72597800908',
    projectId: 'spendwise-ea975',
    authDomain: 'spendwise-ea975.firebaseapp.com',
    storageBucket: 'spendwise-ea975.firebasestorage.app',
    measurementId: 'G-76NRQ8X0VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1RbW4Wd6lPrnuD3g0xFrJ_Zj7y558W5w',
    appId: '1:72597800908:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '72597800908',
    projectId: 'spendwise-ea975',
    storageBucket: 'spendwise-ea975.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1RbW4Wd6lPrnuD3g0xFrJ_Zj7y558W5w',
    appId: '1:72597800908:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '72597800908',
    projectId: 'spendwise-ea975',
    storageBucket: 'spendwise-ea975.firebasestorage.app',
    iosBundleId: 'com.ambtion.spendwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1RbW4Wd6lPrnuD3g0xFrJ_Zj7y558W5w',
    appId: '1:72597800908:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '72597800908',
    projectId: 'spendwise-ea975',
    storageBucket: 'spendwise-ea975.firebasestorage.app',
    iosBundleId: 'com.ambtion.spendwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1RbW4Wd6lPrnuD3g0xFrJ_Zj7y558W5w',
    appId: '1:72597800908:web:b548b6ee1e52609505bf69',
    messagingSenderId: '72597800908',
    projectId: 'spendwise-ea975',
    authDomain: 'spendwise-ea975.firebaseapp.com',
    storageBucket: 'spendwise-ea975.firebasestorage.app',
    measurementId: 'G-76NRQ8X0VW',
  );
}